- hosts: all
  name: Install Apache and PHP
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - mariadb-server
          - mediawiki
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
       
    - name: data 
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdb
     
    - name: data
      ansible.posix.mount:
        path: /var/lib/mysql
        src: /dev/sdb
        fstype: ext4
        state: present 

- hosts: all
  tasks:
    - name: install pip
      apt:
       
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Sets the root password
      mysql_user:
        name: root
        password: "{{ the_flash }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock