- hosts: all
  name: Install Apache and PHP
  become: yes
  tasks:

    - name: Create an ext4 filesystem on /dev/sdb
      community.general.filesystem:
        fstype: ext4
        state: present
        dev: /dev/sdb

    - name: Mount and bind a volume
      ansible.posix.mount:
        path: /var/lib/mysql
        src: /dev/sdb
        opts: 
        state: mounted
        fstype: ext4

    #- name: Fix 'support_tools' permissions
      #shell: 'chmod a+x /var/lib/mysql'


    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - mariadb-server
          - mediawiki
          - python3-pip
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'


  

       


- hosts: all
  tasks:
    - name: install pip
      apt:
       
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Pip Pre-Reqs for SQL
      become: yes
      pip:
        name: PyMySQL

    - name: Enable MySQL
      become: yes
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database for MediaWiki
      become: yes
      become_user: root
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "my_wiki"
        state: present
  

    - name: Create MediaWiki DB user
      become: yes
      become_user: root
      community.mysql.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
        name: "christian"
        password: "the_flash"
        priv:
          "*.*:ALL,GRANT"
        
          